chore: fix deployment health test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -65,8 +65,8 @@ jobs:
 
     - name: Wait for Deployment to be Ready
       run: |
-        kubectl rollout status deployment/whoami-deployment --timeout=60s || { echo "whoami-deployment rollout failed"; exit 1; }
-        kubectl rollout status deployment/whoami-canary --timeout=60s || { echo "whoami-canary rollout failed"; exit 1; }
+        kubectl rollout status deployment/base-app --timeout=60s || { echo "base-app rollout failed"; exit 1; }
+        kubectl rollout status deployment/canary-app --timeout=60s || { echo "canary-app rollout failed"; exit 1; }
 
     - name: Verify Deployment Health
       run: |
